spring:
  application:
    name: user-management

  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/user_management}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always
      schema-locations: classpath:data.sql

server:
  port: 8080
  servlet:
    context-path: /user-management

jwt:
  signerKey: Z3v5NoNIZjszFpUiARpxY+UKApyLEvqWGlCZkZt+/xHyZAHAJczeXbc0a8jJb+Y/
  valid-duration: 3600 # in second
  refreshable-duration: 120 # in second
